# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    strategy:
      matrix:
        r-version: [4.0]

    steps:
      - uses: actions/checkout@v2
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r-version }}
      - name: Checksum comarques_setmanal.csv
        run: if [ `md5sum comarques_setmanal.csv | cut -d ' ' -f 1` == "d8d4a3ffa2cd0e7bbb3b03f8b5b3cdf1" ] ; then exit 0 ; else { echo wrong comarques_setmanal.csv file ; exit 1 ; } ; fi
      - name: Run analysis.R
        run: Rscript analysis.R
      - name: Check results file rnkIA14Oct20byCounty.csv
        run: if [ -e rnkIA14Oct20byCounty.csv ] ; then exit 0 ; else { echo missing results file rnkIA14Oct20byCounty.csv ; exit 1 ; } ; fi
      - name: Checksum rnkIA14Oct20byCounty.csv
        run: if [ `md5sum rnkIA14Oct20byCounty.csv | cut -d ' ' -f 1` == "d95a746e4511b0741fc50acb829e7861" ] ; then exit 0 ; else exit 1 ; fi
